### DISCUSSION TITLE
Help with calculate average price

### DISCUSSION THREAD

**Discussion by Manhem** [custom-components/nordpool#307] [General]
This is not a issue.
I wonder if there is anyone who can help me with a formula.
I would like to get the average price over, let's say, one month from the values from Nordpool.
Is here anyone that has done this and are willing to share this with me?

**Comment by t0xa** [comment]
Hello,

 1. Install "Average" sensor - https://github.com/Limych/ha-average
 2. Open `configuration.yaml` in the "File Editor" Add-on and add following sensor
 
```
sensor:
  - platform: average
    name: 'Average Nordpool Price'
    end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
      days: 30
    entities:
      - sensor.nordpool
```
 3.  Restart Home Assistant.
 4. Add relevant widget on Dashboard

Please note that sensor doesn't work retrospectively and it needs to aggregate data for 30 days to show actual value.
