### ISSUE TITLE
Sensor fails to be created

### ISSUE THREAD

**Issue by tubalainen** [custom-components/nordpool#103]
## Version of the custom_component

0.0.4

## Homeassistant version
2021.12.9 - Home Assistant Container

## Configuration

```yaml

logger:
  default: info
  logs:
    nordpool: debug
    custom_components.nordpool: debug
    custom_components.nordpool.sensor: debug
    custom_components.nordpool.aio_price: debug

nordpool:

sensor:
  - platform: nordpool
    currency: "SEK"
    region: "SE3"
    price_type: kWh
    additional_costs: "{{0.0|float}}"
```
Add your logs here.

[Hastebin](https://www.toptal.com/developers/hastebin/qolanonixo.yaml)

## Describe the bug
The sensors fail to be setup - tried both adding the component manually, via hacs, using the wizard and adding it manually to my configuration.

## Debug log

[Hastebin](https://www.toptal.com/developers/hastebin/qolanonixo.yaml)

Add your logs here.

[Hastebin](https://www.toptal.com/developers/hastebin/qolanonixo.yaml)
