### ISSUE TITLE
Can't create an integration with region SE3 and SEK

### ISSUE THREAD

**Issue by nilaz** [custom-components/nordpool#107]
## Version of the custom_component
0.0.4

## Homeassistant version
Home Assistant 2021.12.9

## Configuration
Using the ui wizard with the following input:
![image](https://user-images.githubusercontent.com/1112093/149362363-b7578f96-ab2c-4d41-a1f8-c4baf89e2dc8.png)

Logging set to
```yaml
logger:
  default: warning
  logs:
    homeassistent.components.mqtt: debug
    pydeconz: debug
    homeassistant.components.deconz: debug
    pymodbus: debug
    homeassistant.components.modbus: debug
    pymodbus.client: debug
    nordpool: debug
    custom_components.nordpool: debug
    custom_components.nordpool.sensor: debug
    custom_components.nordpool.aio_price: debug
```

## Describe the bug
I want to create an integration with region SE3 and currency SEK. I fill in the wizard as shown above. The error is seen in the picture.
It says I should use one of the listed currencies. I have now tried all four mentioned in the message and there is an integration created for the three other currencies in the list, but it does not work for the last one that I would like to use, SEK.
When I look at the three created integrations I see values read for all three of them. The sensors seem to work as they should.

Edit: I have been running Nordpool for some time but since the last update I have not seen anything in my graph. I don't know exactly when it stopped working.

## Debug log

I see nothing in the log
