### ISSUE TITLE
Changing config regenerates entity_id

### ISSUE THREAD

**Issue by magnusoverli** [custom-components/nordpool#115]
## Version of the custom_component

0.0.4
## Homeassistant version
2022.2.0b4

## Configuration

```yaml
- platform: nordpool
  VAT: True
  currency: "NOK"
  region: "Bergen"
  precision: 5
  price_type: kWh
  additional_costs: "{{0.01|float}}"
  low_price_cutoff: 0.95

```

## Describe the bug
The sensor entity_id is regenerated on every config change. This makes it difficult to make adjustments and have the resulting changes be picked up wherever the sensor data is used. I just discovered this great integration yesterday, but already today, when changing the config, needed to update the HA config in 6 places to match the regenerated `entity_id`.
