### ISSUE TITLE
Unable to get automation to work on nordpool sensor

### ISSUE THREAD

**Issue by woopstar** [custom-components/nordpool#122]
## Version of the custom_component
0.0.4

## Homeassistant version
Home Assistant 2022.3.2

## Configuration
```
id: '1646662514726'
alias: Nordpool kWh Above 7 - Set Metrotherm to Økonomi
description: ''
trigger:
  - type: value
    platform: device
    device_id: 820ee8abc48809a23aac01b23fdd50fe
    entity_id: sensor.nordpool_kwh_dk1_dkk_2_00_025
    domain: sensor
    above: 7.1
condition:
  - type: is_value
    condition: device
    device_id: 820ee8abc48809a23aac01b23fdd50fe
    entity_id: sensor.nordpool_kwh_dk1_dkk_2_00_025
    domain: sensor
    above: 7.1
action:
  - service: shell_command.metroterm_komfort_okonomi
    data: {}
  - device_id: 55cf63611d677863a4ac101750577aa7
    domain: mobile_app
    type: notify
    message: Nordpool kWh Above 7 - Set Metrotherm to Økonomi
    title: Metrotherm
mode: single
```

## Describe the bug
Adding automation to the nordpool entity does not seem to work. The automation is always on, even though the sensor reports a value of less than 7.1. 

I was testing using 7.1 and not 7, to make sure it was not an int vs float bug.

## Pictures for debug:
Setup of integration:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/2997782/157190919-e4768570-7a5e-42b7-b72c-5ced4ab1cb7e.png">

Current value of sensor:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/2997782/157190801-218e4d5c-9204-48f1-ac3f-4b054a9da190.png">

History:
<img width="2263" alt="image" src="https://user-images.githubusercontent.com/2997782/157191598-69b2415e-e9c2-41d0-b663-67fc1b3558a0.png">
