### ISSUE TITLE
No module named 'nordpool.elspot'

### ISSUE THREAD

**Issue by erikarenhill** [custom-components/nordpool#140]
## Version of the custom_component
0.0.5 installed through HACS

## Homeassistant version
2022.4.5
Host Operating System | Home Assistant OS 7.6
Update Channel | stable
Supervisor Version | supervisor-2022.04.0

## Configuration

```yaml
#tried with both through config flow and configuration.yaml, when using config the below was used

nordpool: 

logger:
  default: error
  logs:
    # log level for HA core
    homeassistant.core: fatal
    nordpool: debug
    custom_components.nordpool: debug
    custom_components.nordpool.sensor: debug
    custom_components.nordpool.aio_price: debug

sensor:
   - platform: nordpool
     currency: "SEK"
     region: "SE4"
     precision: 3

```

## Describe the bug
When trying to add the integration through the UI it yields this error message:
```
Error occurred loading configuration flow for integration nordpool: No module named 'nordpool.elspot'
```
When trying to use configuration.yaml (I didnt use them both at the same time) it gives a similiar message.

## Debug log

Enabled 
```text

Logger: homeassistant.config_entries
Source: config_entries.py:745
First occurred: 2:56:46 PM (2 occurrences)
Last logged: 2:59:07 PM

Error occurred loading configuration flow for integration nordpool: No module named 'nordpool.elspot'

```

It used to work a couple of releases ago, and suddenly it stopped working. I also tried uninstalling it through HACS and reinstalling without any success.
