### ISSUE TITLE
Incorrect prices

### ISSUE THREAD

**Issue by NicklasRaab** [custom-components/nordpool#177]
## Version of the custom_component
0.0.7

## Homeassistant version
Home Assistant 2022.8.2
Supervisor 2022.07.0
Operating System 8.4
Frontend-version: 20220802.0 - latest

## Configuration

```yaml

nordpool:

sensor:
  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: True

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currency
    currency: "SEK"
    
    # Option to show prices in cents (or the equivalent in local currency)
    price_in_cents: false

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "SE4"

    # How many decimals to use in the display of the price
    precision: 3

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    additional_costs: "{{0.0|float}}"

```

## Describe the bug
The sensor in HA gives me different prices compared to when just looking at the table at the website.

The readout from the sensor looks image 1 called sensor.png.
The information on their website looks like image 2 called website.png.
![sensor](https://user-images.githubusercontent.com/10383535/183643748-c2f94006-9a4b-4c44-a6df-a678f492e377.PNG)
![website](https://user-images.githubusercontent.com/10383535/183643919-f9507b64-eddd-44d5-a59c-b477ed39fd06.PNG)

The dates are double checked that they are the same. Any ideas what I'm doing wrong?
