### ISSUE TITLE
Three first hours keep old value in HA history

### ISSUE THREAD

**Issue by elektrinis** [custom-components/nordpool#185]
## Describe the bug
Every night after midnight the same value is recorded for first three hours.
In my graph below I have history and forecast overlapping, where you can clearly see that initial three hours are incorrect. It is logged this way every day.
https://i.imgur.com/StVoGlt.png

## Version of the custom_component
Latest from HACS (0.0.7)

## Homeassistant version
2022.8.5

## Configuration

```yaml

type: custom:apexcharts-card
graph_span: 71h
span:
  end: day
  offset: +1d
header:
  show: true
  show_states: true
  colorize_states: true
hours_12: false
stacked: false
experimental:
  color_threshold: true
all_series_config:
  show:
    legend_value: false
    datalabels: false
  float_precision: 2
  extend_to: false
  fill_raw: 'null'
  color_threshold:
    - value: 20
      color: 50FF00
    - value: 40
      color: FF5000
now:
  show: true
  label: Now
  color: red
series:
  - entity: sensor.nordpool_kwh_lt_eur_3_00_021
    name: Now
    opacity: 1
    type: line
    curve: stepline
    stroke_width: 1
    show:
      extremas: false
  - entity: sensor.nordpool_kwh_lt_eur_3_00_021
    name: Now
    opacity: 1
    type: line
    curve: stepline
    stroke_width: 1
    show:
      extremas: true
      in_header: false
    data_generator: |
      if(entity.attributes.tomorrow_valid) {
        return (entity.attributes.raw_today.map((start, index) => {
          return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
        })).concat(entity.attributes.raw_tomorrow.map((start, index) => {
          return [new Date(start["start"]).getTime(), entity.attributes.raw_tomorrow[index]["value"]];
        }))
      } else { 
        return (entity.attributes.raw_today.map((start, index) => {
          return [new Date(start["start"]).getTime(), entity.attributes.raw_today[index]["value"]];
        }))
      };
apex_config:
  tooltip:
    fixed:
      enabled: true
      position: topRight
      offsetY: 10
      offsetX: -25
    followCursor: true
  chart:
    height: 300px
  title:
    text: Nordpool
    align: Center
  xaxis:
    type: datetime
    tickAmount: 12
    labels:
      show: true
      rotate: -45
      rotateAlways: true
  yaxis:
    decimalsInFloat: 0
  legend:
    show: false
  grid:
    show: true
    xaxis:
      lines:
        show: true
    yaxis:
      lines:
        show: true
    position: back
    strokeDashArray: 1


```
