### ISSUE TITLE
Conflicting configuration GUI vs. yaml

### ISSUE THREAD

**Issue by elektrinis** [custom-components/nordpool#186]
## Describe the bug
I have specified incorrect values when installing this component. Then I have added a different configuration in configuration.yaml.
I ended up with two different entities, one from GUI and one from yaml:
sensor.nordpool_kwh_lt_eur_3_10_0
sensor.nordpool_kwh_lt_eur_3_00_021

However only one of them (GUI) is displayed in "device" list.
https://i.imgur.com/gUoeNmY.png
https://i.imgur.com/aNNExBi.png

## Version of the custom_component
0.0.7

## Homeassistant version
2022.8.5

## Configuration

```yaml

  - platform: nordpool
    VAT: true
    currency: "EUR"
    price_in_cents: true
    low_price_cutoff: 0.00
    region: "LT"
    precision: 3
    price_type: kWh
    additional_costs: "{{0.09|float}}"

```
