### ISSUE TITLE
LowPrice = Null When price is 0. 

### ISSUE THREAD

**Issue by zipperten** [custom-components/nordpool#202]
## Version of the custom_component
Version 0.0.7

## Homeassistant version
 Home Assistant 2022.10.1 Supervisor 2022.09.1 Operating System 9.0 Frontend-version: 20221006.0 - latest 

## Configuration

```yaml

Add your configuration here.

- platform: nordpool
  # Should the prices include vat? Default True
  VAT: True
    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currecy
#   currency: "EUR"
    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
  low_price_cutoff: '0.90'
    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS"
  region: 'SE4'
    # How many decimals to use in the display of the price
  precision: '3'
    # What the price should be displayed in default
    # Possible values: mwh, kwh and w
    # default: kwh
  price_type: 'kWh'
  friendly_name: 'Power'

```

## Debug log

```LowPrice = Null When price is 0. 

Add your logs here.
