### ISSUE TITLE
Prices 1000 times smaller than they should be. (With €/MWh)

### ISSUE THREAD

**Issue by roolijoodik7** [custom-components/nordpool#219]
Hello, 
On 11 november I updated the nordpool custom component to version 0.0.8 (from 0.0.7). At the same time I also updated Home Assistant. Since then all the prices shown are 1000 times smaller than they should be. I tried to restore a backup, but still the same problem.
Here is my configuration:
```
sensor:
  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: true

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currency
    currency: "EUR"
    
    # Option to show prices in cents (or the equivalent in local currency)
    price_in_cents: false

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.01

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "EE"

    # How many decimals to use in the display of the price
    precision: 3

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: MWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    additional_costs: "{{0.0|float}}" 
```
My price is with tax:
![image](https://user-images.githubusercontent.com/116514944/201487867-81650482-7990-40ee-aa2a-574c8558a7d9.png)

This is price on Nordpool website:
![image](https://user-images.githubusercontent.com/116514944/201487956-3bb8ad81-5665-4c92-8385-51b1d34e770e.png)

Is the problem only on my system or is it some bug in code? 
Best regards
