### ISSUE TITLE
Zero search results for nordpool, error message with manual install

### ISSUE THREAD

**Issue by winny-git** [custom-components/nordpool#234]
The logs didn’t really tell me anything except that the has loaded the component. Anyway. With ui I meant the web ui: Configuration > Integration > search for nordpool. You should also try to install it using hacs instead of manual install.

https://www.home-assistant.io/integrations/logger/ Link for how you can setup the logger so we can get some debug info.

_Originally posted by @Hellowlol in https://github.com/custom-components/nordpool/issues/17#issuecomment-593132850_

I have the same issue as in the closed issue above.

Searching for nordpool under Add integration gives zero results.

Downloading the master branch version form github and extracting the zip file to `/opt/homeassistant/config/custom_components/nordpool` and adding the following to `/opt/homeassistant/config/configuration.yaml`:

```
#Nordpool
nordpool:

sensor:
  - platform: nordpool
    region: "SE3"
    VAT: True
    currency: "SEK"
    low_price_cutoff: 1
```

gives the following error message:

Configuration invalid!

Integration error: nordpool - Integration 'nordpool' not found.
Platform error sensor.nordpool - Integration 'nordpool' not found.
