### ISSUE TITLE
Min and Max are not correctly calculated with Additional costs

### ISSUE THREAD

**Issue by nicochi** [custom-components/nordpool#238]
## Version of the custom_component
0.0.9

## Homeassistant version
Home Assistant 2022.12.7
Supervisor 2022.11.2
Frontend 20221213.1 - latest

## Configuration

```yaml

  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: true

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currency
    currency: "NOK"
    
    # Option to show prices in cents (or the equivalent in local currency)
    price_in_cents: false

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "Tr.heim"

    # How many decimals to use in the display of the price
    precision: 3

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    #additional_costs: "{{0.0|float}}"
    
    additional_costs: '{% set s = {
        "hourly_fixed_cost": 0.0,
        "winter_day": 0.3020,
        "winter_night": 0.2145,
        "summer_day": 0.3855,
        "summer_night": 0.2980,
        "cert": 0.01
        }
      %}
      {% if now().month >= 4 and now().month <=12 %}
        {% if now().hour >=6 and now().hour <22 %}
          {{s.summer_day+s.hourly_fixed_cost+s.cert|float}}
        {% else %}
          {{s.summer_night+s.hourly_fixed_cost+s.cert|float}}
        {% endif %}
      {% else %}
        {% if now().hour >=6 and now().hour <22 %}
          {{s.winter_day+s.hourly_fixed_cost+s.cert|float}}
        {%else%}
          {{s.winter_night+s.hourly_fixed_cost+s.cert|float}}
        {% endif %}
      {% endif %}'

```

## Describe the bug

Max and Min Attributes are scaled with additional_cost using the time the data is pulled and not the actual time the Min and Max are, therefore it is not correct. 

Case 1 - both min and max were doring night time and update pulled during day time - apply summer_day additional cost scheme::
Max reported: 1.7 - Actual Max from Today cost list: 1.611 (additional cost applied is 0.3955 instead of 0.3080)
Min reported: 1.06 - Actual Min from Today cost list: 0.977 (additional cost applied is 0.3955 instead of 0.3080)

Case 2 - min time during night, max during day. nordpool pulled at night time - apply summer_night additional cost scheme:
Max reported: 1.81 - Actual Max from Today cost list: 1.895  (additional cost applied is 0.3080 instead of 0.3955)
Min reported:  1.04 - Actual Min from Today cost list:  1.037 (additional cost applied is 0.3080  - correct as both pulling and min is at night time)

Possibly also Average, Off Peak 1, Off Peak 2, Peak attributes pulled from nordpool are scaled wrongly.

Example 1 output:

Current price
0.98
Average
1.41
Off peak 1
1.51
Off peak 2
1.12
Peak
1.43
**Min
1.06
Max
1.7**
Unit
kWh
Currency
NOK
Country
Norway
Region
Tr.heim
Low price
true
Price percent to average
0.69
Today
**1.611**, 1.599, 1.497, 1.414, 1.33, 1.226, 1.449, 1.428, 1.424, 1.45, 1.507, 1.58, 1.603, 1.599, 1.532, 1.417, 1.349, 1.261, 1.25, 1.198, 1.182, 1.142, 1.015, **0.977**
Tomorrow
1.037, 1.097, 1.094, 1.175, 1.308, 1.36, 1.388, 1.437, 1.557, 1.634, 1.684, 1.719, 1.719, 1.848, 1.895, 1.875, 1.848, 1.724, 1.702, 1.689, 1.652, 1.632, 1.682, 1.556
....
Additional costs current hour
0.31

Example 1 with zero additional cost:

Current price
0.67
Average
1.01
Off peak 1
1.11
Off peak 2
0.73
Peak
1.04
Min
0.67
Max
1.3
Unit
kWh
Currency
NOK
Country
Norway
Region
Tr.heim
Low price
true
Price percent to average
0.66
Today
1.303, 1.291, 1.189, 1.106, 1.022, 0.918, 1.054, 1.033, 1.029, 1.055, 1.112, 1.185, 1.208, 1.203, 1.137, 1.022, 0.954, 0.865, 0.854, 0.802, 0.787, 0.746, 0.707, 0.669
Tomorrow
0.729, 0.789, 0.786, 0.867, 1, 1.052, 0.993, 1.041, 1.162, 1.239, 1.289, 1.323, 1.323, 1.452, 1.499, 1.48, 1.452, 1.329, 1.306, 1.293, 1.256, 1.237, 1.287, 1.248
...
Additional costs current hour
0

Example 2 output:

Current price
1.04
Average
1.49
Off peak 1
1.22
Off peak 2
1.57
Peak
1.65
**Min
1.04
Max
1.81**
Unit
kWh
Currency
NOK
Country
Norway
Region
Tr.heim
Low price
true
Price percent to average
0.69
Today
**1.037**, 1.097, 1.094, 1.175, 1.308, 1.36, 1.388, 1.437, 1.557, 1.634, 1.684, 1.719, 1.719, 1.848, **1.895**, 1.875, 1.848, 1.724, 1.702, 1.689, 1.652, 1.632, 1.595, 1.556
Tomorrow
Tomorrow valid
false
....
Additional costs current hour
0.31

Example 2 with zero additional cost:

Current price
0.73
Average
1.19
Off peak 1
0.91
Off peak 2
1.26
Peak
1.35
Min
0.73
Max
1.5
Unit
kWh
Currency
NOK
Country
Norway
Region
Tr.heim
Low price
true
Price percent to average
0.62
Today
0.729, 0.789, 0.786, 0.867, 1, 1.052, 0.993, 1.041, 1.162, 1.239, 1.289, 1.323, 1.323, 1.452, 1.499, 1.48, 1.452, 1.329, 1.306, 1.293, 1.256, 1.237, 1.287, 1.248
Tomorrow
Tomorrow valid
false
...
Additional costs current hour
0

## Debug log

```text

Add your logs here.

```
