### ISSUE TITLE
problem getting the additional_cost to work

### ISSUE THREAD

**Issue by ruteclrp** [custom-components/nordpool#263]
0.0.9 Version of the custom_component

2022.12.9 Homeassistant version

## Configuration

```yaml

sensor:
  - platform: nordpool
    # Country/region to get the energy prices for. 
    region: "DK2"
    
    # Override HA local currency used to fetch the prices from the API.
    currency: "DKK"
    
    # Add Value Added Taxes (VAT)?
    VAT: True
    
    # Energy price rounding precision.
    precision: 3
    
    # Display price in cents in stead of (for example) Euros.
    price_in_cents: false

    # Price displayed for MWh, kWh or Wh
    price_type: kWh

    # Template to specify additional cost to be added to the tariff.
    # The template price is in EUR, DKK, NOK or SEK (not in cents).
    # For example: "{{ current_price * 0.19 + 0.023 | float}}" 
    additional_costs: "{{0.0|float}}"
    
    {% if now().hour >= 0 and now().hour < 6 %}
        {{ current_price + 0.210 | float }}
    {% if now().hour >= 6 and now().hour < 17 %}
        {{ current_price + 0.640 | float }}
    {% if now().hour >= 17 and now().hour < 21 %}
        {{ current_price + 1.910 | float }}
    {% if now().hour >= 21 and now().hour < 24 %}
        {{ current_price + 0.640 | float }}
    {% endif %}
```

## Describe the bug
The syntax of the if statements is not accepted - claim some missing (,)

Unable to figure out what the reason is, but then, I am also not yet an avid HA nerd.
