### ISSUE TITLE
Feat: add `average` for tomorrow's prices

### ISSUE THREAD

**Issue by hmmbob** [custom-components/nordpool#267]
**Is your feature request related to a problem? Please describe.**
The sensor provides the average price for today's prices, but doesn't do so for tomorrow (as soon as tomorrow's prices are known, of course). It would be great to have both available.

**Describe the solution you'd like**
Add an attribute `average_tomorrow: ` with tomorrow's average price, as soon as tomorrow's data is known.

**Describe alternatives you've considered**
I'm using a `template` sensor now:

```yaml
- sensor:
    - name: "Nordpool Tomorrow Average"
      unique_id: nordpool_tomorrow_average
      state: "{{ average(states['sensor.nordpool'].attributes.tomorrow, 0) | round(3) }}"
```
 but I'd like to get rid of this.

**Additional context**
I'm using this value to show the average price for the day in the chart:

![image](https://user-images.githubusercontent.com/33529490/211148672-c976aa60-f082-40dc-96dc-80dd1e39e98d.png)
