### ISSUE TITLE
Additional Cost adds to much

### ISSUE THREAD

**Issue by djjoakim** [custom-components/nordpool#270]
## Homeassistant version
2023.1.1

## Configuration

```yaml

sensor nordpool:
  - platform: nordpool
    # Should the prices include vat? Default True
    VAT: True

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currency
    currency: "SEK"

    # Option to show prices in cents (or the equivalent in local currency)
    price_in_cents: False

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "SE3"

    # How many decimals to use in the display of the price
    precision: 2

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    additional_costs: "{{current_price + 0.14}}"

```

## Describe the bug
The price now is 0,80 SEK with taxes, but my price now is 0.94 SEK since i got 14 cents in extra certificates taxes (Sweden...)
With the "additional_cost" i wan't to add 0.14 to the price, to get my correct price, but instead of showing 0.94, Nordpool shows 1.75 SEK, and if i see the "additional_cost" it says "additional_costs_current_hour: 1.267575"

I have tried disable VAT, show/dont show cents, nothing works.
What am i doing wrong?

Thanks
