### ISSUE TITLE
Decimal precision not working after upgrade from 0.0.9 to 0.0.10

### ISSUE THREAD

**Issue by imfoffo** [custom-components/nordpool#271]
Before the upgrade decimal precision was set to the value of 2 and the price was shown currently.
After upgrading to version 0.0.10 precision seems to be ignored, and the price is shown with 7 decimals. 
The upgrade is the only change.

From configuration.yaml

```
sensor:
  - platform: nordpool

    # Should the prices include vat? Default True
    VAT: True

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currency
    currency: "DKK"

    # Option to show prices in cents (or the equivalent in local currency)
    price_in_cents: false

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4>
    region: "DK2"

    # How many decimals to use in the display of the price
    precision: 2

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

    # This option allows the usage of a template to add a tariff.
    # now() always refers start of the hour of that price.
    # this way we can calculate the correct costs add that to graphs etc.
    # The price result of the additional_costs template expects this additional cost to be in kWh and not cents as a float
    # default {{0.0|float}}
    additional_costs: "{{1.59|float}}"
```
