### ISSUE TITLE
Decimal precision is ignored 

### ISSUE THREAD

**Issue by muddenhed** [custom-components/nordpool#279]
## Version of the custom_component
0.0.10

## Homeassistant version
2023.1.6

## Configuration

```yaml

## NordPool
  - platform: nordpool
    # Should the prices include vat? Default True
    VAT: True
    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currecy
    currency: "SEK"
    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "SE4"
    # How many decimals to use in the display of the price
    precision: 2
    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh
```

## Describe the bug
Do not honor decimal settings anymore, shows 4 decimals when set to show only 2.

![Screenshot at Jan 20 15-18-56](https://user-images.githubusercontent.com/8309791/213721086-5f627be2-b396-48f4-86ab-f7d971de8e7c.png)
