### ISSUE TITLE
Between 00-01 the today and tomorrow datetime and price data is the same

### ISSUE THREAD

**Issue by lovekull76** [custom-components/nordpool#284]
## Version of the custom_component

0.0.10

## Homeassistant version
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

## Configuration

```yaml

sensor:
  - platform: nordpool
    region: "SE1"
    currency: "SEK"    
    VAT: True    
    precision: 3
    low_price_cutoff: 0.95
    price_in_cents: false
    price_type: kWh
    additional_costs: "{{0.4335 | float}}"
```

## Describe the bug
After midnight the data, both timestamps and prices, are the same for today and tomorrow attributes. And tomorrow_valid = true.
It is like if when we pass midnight today data updates but the tomorrow data is not updated/reset to null. 
If I reload the integration the tomorrow attributes is reset to null and with tomorrow dates.

At 2023-01-29 00:03 the sensor.nordpool has the following attributes:

```yaml
state_class: measurement
average: 0.8610890625
off_peak_1: 0.834025
off_peak_2: 0.777978125
peak: 0.9068354166666667
min: 0.69155
max: 0.949175
mean: 0.86025
unit: kWh
currency: SEK
country: Sweden
region: SE1
low_price: false
price_percent_to_average: 0.9897059864234428
today:
  - 0.852225
  - 0.8460375
  - 0.8326749999999999
  - 0.8307
  - 0.8361875
  - 0.81325
  - 0.81705
  - 0.8440749999999999
  - 0.868275
  - 0.8740375
  - 0.9169499999999999
  - 0.9118875
  - 0.9103375
  - 0.9252499999999999
  - 0.9172374999999999
  - 0.89135
  - 0.9216
  - 0.949175
  - 0.92385
  - 0.8720749999999999
  - 0.8349249999999999
  - 0.79905
  - 0.7863875
  - 0.69155
tomorrow:
  - 0.852225
  - 0.8460375
  - 0.8326749999999999
  - 0.8307
  - 0.8361875
  - 0.81325
  - 0.81705
  - 0.8440749999999999
  - 0.868275
  - 0.8740375
  - 0.9169499999999999
  - 0.9118875
  - 0.9103375
  - 0.9252499999999999
  - 0.9172374999999999
  - 0.89135
  - 0.9216
  - 0.949175
  - 0.92385
  - 0.8720749999999999
  - 0.8349249999999999
  - 0.79905
  - 0.7863875
  - 0.69155
tomorrow_valid: true
raw_today:
  - start: '2023-01-29T00:00:00+01:00'
    end: '2023-01-29T01:00:00+01:00'
    value: 0.852225
  - start: '2023-01-29T01:00:00+01:00'
    end: '2023-01-29T02:00:00+01:00'
    value: 0.8460375
  - start: '2023-01-29T02:00:00+01:00'
    end: '2023-01-29T03:00:00+01:00'
    value: 0.8326749999999999
  - start: '2023-01-29T03:00:00+01:00'
    end: '2023-01-29T04:00:00+01:00'
    value: 0.8307
  - start: '2023-01-29T04:00:00+01:00'
    end: '2023-01-29T05:00:00+01:00'
    value: 0.8361875
  - start: '2023-01-29T05:00:00+01:00'
    end: '2023-01-29T06:00:00+01:00'
    value: 0.81325
  - start: '2023-01-29T06:00:00+01:00'
    end: '2023-01-29T07:00:00+01:00'
    value: 0.81705
  - start: '2023-01-29T07:00:00+01:00'
    end: '2023-01-29T08:00:00+01:00'
    value: 0.8440749999999999
  - start: '2023-01-29T08:00:00+01:00'
    end: '2023-01-29T09:00:00+01:00'
    value: 0.868275
  - start: '2023-01-29T09:00:00+01:00'
    end: '2023-01-29T10:00:00+01:00'
    value: 0.8740375
  - start: '2023-01-29T10:00:00+01:00'
    end: '2023-01-29T11:00:00+01:00'
    value: 0.9169499999999999
  - start: '2023-01-29T11:00:00+01:00'
    end: '2023-01-29T12:00:00+01:00'
    value: 0.9118875
  - start: '2023-01-29T12:00:00+01:00'
    end: '2023-01-29T13:00:00+01:00'
    value: 0.9103375
  - start: '2023-01-29T13:00:00+01:00'
    end: '2023-01-29T14:00:00+01:00'
    value: 0.9252499999999999
  - start: '2023-01-29T14:00:00+01:00'
    end: '2023-01-29T15:00:00+01:00'
    value: 0.9172374999999999
  - start: '2023-01-29T15:00:00+01:00'
    end: '2023-01-29T16:00:00+01:00'
    value: 0.89135
  - start: '2023-01-29T16:00:00+01:00'
    end: '2023-01-29T17:00:00+01:00'
    value: 0.9216
  - start: '2023-01-29T17:00:00+01:00'
    end: '2023-01-29T18:00:00+01:00'
    value: 0.949175
  - start: '2023-01-29T18:00:00+01:00'
    end: '2023-01-29T19:00:00+01:00'
    value: 0.92385
  - start: '2023-01-29T19:00:00+01:00'
    end: '2023-01-29T20:00:00+01:00'
    value: 0.8720749999999999
  - start: '2023-01-29T20:00:00+01:00'
    end: '2023-01-29T21:00:00+01:00'
    value: 0.8349249999999999
  - start: '2023-01-29T21:00:00+01:00'
    end: '2023-01-29T22:00:00+01:00'
    value: 0.79905
  - start: '2023-01-29T22:00:00+01:00'
    end: '2023-01-29T23:00:00+01:00'
    value: 0.7863875
  - start: '2023-01-29T23:00:00+01:00'
    end: '2023-01-30T00:00:00+01:00'
    value: 0.69155
raw_tomorrow:
  - start: '2023-01-29T00:00:00+01:00'
    end: '2023-01-29T01:00:00+01:00'
    value: 0.852225
  - start: '2023-01-29T01:00:00+01:00'
    end: '2023-01-29T02:00:00+01:00'
    value: 0.8460375
  - start: '2023-01-29T02:00:00+01:00'
    end: '2023-01-29T03:00:00+01:00'
    value: 0.8326749999999999
  - start: '2023-01-29T03:00:00+01:00'
    end: '2023-01-29T04:00:00+01:00'
    value: 0.8307
  - start: '2023-01-29T04:00:00+01:00'
    end: '2023-01-29T05:00:00+01:00'
    value: 0.8361875
  - start: '2023-01-29T05:00:00+01:00'
    end: '2023-01-29T06:00:00+01:00'
    value: 0.81325
  - start: '2023-01-29T06:00:00+01:00'
    end: '2023-01-29T07:00:00+01:00'
    value: 0.81705
  - start: '2023-01-29T07:00:00+01:00'
    end: '2023-01-29T08:00:00+01:00'
    value: 0.8440749999999999
  - start: '2023-01-29T08:00:00+01:00'
    end: '2023-01-29T09:00:00+01:00'
    value: 0.868275
  - start: '2023-01-29T09:00:00+01:00'
    end: '2023-01-29T10:00:00+01:00'
    value: 0.8740375
  - start: '2023-01-29T10:00:00+01:00'
    end: '2023-01-29T11:00:00+01:00'
    value: 0.9169499999999999
  - start: '2023-01-29T11:00:00+01:00'
    end: '2023-01-29T12:00:00+01:00'
    value: 0.9118875
  - start: '2023-01-29T12:00:00+01:00'
    end: '2023-01-29T13:00:00+01:00'
    value: 0.9103375
  - start: '2023-01-29T13:00:00+01:00'
    end: '2023-01-29T14:00:00+01:00'
    value: 0.9252499999999999
  - start: '2023-01-29T14:00:00+01:00'
    end: '2023-01-29T15:00:00+01:00'
    value: 0.9172374999999999
  - start: '2023-01-29T15:00:00+01:00'
    end: '2023-01-29T16:00:00+01:00'
    value: 0.89135
  - start: '2023-01-29T16:00:00+01:00'
    end: '2023-01-29T17:00:00+01:00'
    value: 0.9216
  - start: '2023-01-29T17:00:00+01:00'
    end: '2023-01-29T18:00:00+01:00'
    value: 0.949175
  - start: '2023-01-29T18:00:00+01:00'
    end: '2023-01-29T19:00:00+01:00'
    value: 0.92385
  - start: '2023-01-29T19:00:00+01:00'
    end: '2023-01-29T20:00:00+01:00'
    value: 0.8720749999999999
  - start: '2023-01-29T20:00:00+01:00'
    end: '2023-01-29T21:00:00+01:00'
    value: 0.8349249999999999
  - start: '2023-01-29T21:00:00+01:00'
    end: '2023-01-29T22:00:00+01:00'
    value: 0.79905
  - start: '2023-01-29T22:00:00+01:00'
    end: '2023-01-29T23:00:00+01:00'
    value: 0.7863875
  - start: '2023-01-29T23:00:00+01:00'
    end: '2023-01-30T00:00:00+01:00'
    value: 0.69155
current_price: 0.852225
additional_costs_current_hour: 0.4335
unit_of_measurement: SEK/kWh
device_class: monetary
icon: mdi:flash
friendly_name: nordpool
```
raw_today and raw_tomorrow is the same data!
 
## Debug log

```text
N/A
```
