### ISSUE TITLE
entity is no longer provided by the integration - unavailable since 4 pm october 14th

### ISSUE THREAD

**Issue by typxxi** [custom-components/nordpool#417]
## Version of the custom_component
latest: 0.0.14

## Homeassistant version
![image](https://github.com/user-attachments/assets/1bbcdaf6-4119-428a-b8ba-78256d447e55)

## Configuration
  - platform: nordpool
    region: "DE-LU"      # Country/region to get the energy prices for. 
    currency: "EUR"
    VAT: True            # Add Value Added Taxes (VAT)?
    precision: 3         # Energy price rounding precision.
    price_in_cents: true # Display price in cents in stead of (for example) Euros.
    price_type: kWh      # Price displayed for MWh, kWh or Wh
  
    #Percentage of average price to set the low price attribute
    #low_price = hour_price < average * low_price_cutoff
    low_price_cutoff: 0.95

    #Template to specify additional cost to be added to the tariff.
    #The template price is in EUR, DKK, NOK or SEK (not in cents).
    #For example: "{{ current_price * 0.19 + 0.023 | float}}" 

    additional_costs: "{{ (0.2027 + (current_price * 0.19)) | float }}"

## Describe the bug
entity is no longer provided by the integration
![image](https://github.com/user-attachments/assets/92db851e-985d-4345-b8f0-915379cc0e3a)

## Debug log
![image](https://github.com/user-attachments/assets/09d830bf-2f43-49fb-9f46-04148ded3dc8)

**Comment by lindsand** [comment]
Same for Finland after last  restart, version 0.0.14, and HA version 2024.10.2

This link doesn't lead anywhere:

File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1243, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 404, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=15-10-2024'

Page Not Found
The page you're looking for doesn't exist.

We hope you'll find what you need on our website: [nordpoolgroup.com](https://www.nordpoolgroup.com/)

If you're searching for Market Data, you can find it on our [Data Portal](https://data.nordpoolgroup.com/).

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 09:16:05 (2 occurrences)
Last logged: 10:13:24

Error setting up entry Nordpool for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError(
ValueError: Config entry Nordpool (01J7KR6QMDV34E6ND7M5HWS7X0) for nordpool.sensor has already been setup!



Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 09:15:31 (2 occurrences)
Last logged: 09:19:07

Error setting up entry Nordpool for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/aio_price.py", line 228, in fetch
    res = await asyncio.gather(*jobs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/aio_price.py", line 182, in _fetch_json
    return await self._io(
           ^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/aio_price.py", line 171, in _io
    return await resp.json()
           ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 80, in json
    return await super().json(*args, loads=loads, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1243, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 404, message='Attempt to decode JSON with unexpected mimetype: text/html', url='https://www.nordpoolgroup.com/api/marketdata/page/10?currency=EUR&endDate=15-10-2024'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 131, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 194, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 644, in async_add_entities
    await add_func(coros, entities, timeout)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 595, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 909, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1365, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/nordpool/sensor.py", line 516, in async_added_to_hass
    await self.handle_new_hr()
  File "/config/custom_components/nordpool/sensor.py", line 478, in handle_new_hr
    today = await self._api.today(self._area, self._currency)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 127, in today
    return await self._someday(area, currency, "today")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/__init__.py", line 111, in _someday
    await self.update_today(areas=self.areas)
  File "/config/custom_components/nordpool/__init__.py", line 87, in update_today
    await self._update("today", areas=self.areas if len(self.areas) > 0 else None)
  File "/config/custom_components/nordpool/__init__.py", line 78, in _update
    data = await spot.hourly(end_date=dt, areas=self.areas if len(self.areas) > 0 else None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/aio_price.py", line 244, in hourly
    return await self.fetch(self.HOURLY, end_date, areas)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/backoff/_async.py", line 183, in retry
    await asyncio.sleep(seconds)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout

**Comment by michaelehlers** [comment]
Same for me (also DE-LU), also 14th. I was suspecting the problem being the API change referenced to in the 0.0.15 release notes. Maybe that is the problem as I also have 0.0.14 installed. At least it is what is shown on the 'local' integrations page. I have no option to update to 0.0.15 in 'updates' of home assistant. Just a thought what COULD be the problem. Did not do detailed logging but what I personally get is:

2024-10-15 09:05:18.981 DEBUG (MainThread) [custom_components.nordpool] Added nordpool to hass.data
2024-10-15 09:05:18.987 DEBUG (MainThread) [custom_components.nordpool.sensor] Dumping config mappingproxy({'region': 'DE-LU', 'currency': 'EUR', 'VAT': True, 'precision': 3, 'low_price_cutoff': 1.0, 'price_in_cents': True, 'price_type': 'kWh', 'additional_costs': '{{0.153|float}}'})
2024-10-15 09:05:18.987 DEBUG (MainThread) [custom_components.nordpool.sensor] timezone set in ha 'Europe/Berlin'
2024-10-15 09:05:18.988 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up nordpool platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/nordpool/sensor.py", line 129, in async_setup_entry
    _dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/nordpool/sensor.py", line 104, in _dry_setup
    sensor = NordpoolSensor(
             ^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/sensor.py", line 166, in __init__
    self._vat = _REGIONS[area][2]
                ~~~~~~~~^^^^^^
KeyError: 'DE-LU'

**Comment by lindsand** [comment]
I updated to 0.0.15 and rebooted,  now the values are
- though the device still shows 0.0.14 #418

nordpool
Version 0.0.15 will be downloaded

**Comment by michaelehlers** [comment]
maybe that is the reason that no update is shown by HA 'update function' and so if you do not update manually you still have the version in place that does not work with the changed api. but just a wild speculation (sorry if that does not technically help)

**Comment by typxxi** [comment]
OK, 
at least I am not alone and have caused it somehow somewhere due to improving other parts yesterday cause I had been using it on sunday a lot to get the card for tomorrows "day ahead prices " hidden till 1 p.m. each day to get rid of the empty chart.

And then out of nowhere yesterday todays chart was empty while the reminder for tomorrow release date was shown properly.
That says that the day ahead prices for tomorrow will become available at 1pm so please stay patient.

![image](https://github.com/user-attachments/assets/7764e1af-db94-4c5a-9ef5-03f25c2b7e75)

I hope that there will be a fix soon cause during autumn the car will be charged based on these prices during the night if the day ahead expectation for surplus solar power are low. And that is based on these dynamic tibber  prices.

Still a shame that tibber is not able to get their solution working again when the depreciation of the mathplot libary killed it 6 months ago or even longer when I became a customer and the prices disappeared.

Thanks for sharing the progress.

**Comment by michaelehlers** [comment]
just a thought. Does one of you DE-LU users have the configuration 'adjustable' (in configuration.yam) and some minutes ? If I would do I would try changing DE-LU with GER, reload an test again. The reason I would try this is that first of all many germans commenting here (not only but....), secondly in my logs I see a key error (DE-LU) -> can be all and nothing and I did see on https://data.nordpoolgroup.com/auction/day-ahead/prices that germany is labeled 'GER' and the others seem to match the configuration parameter. Maybe that could be an easy try on error. Just a thought

**Comment by typxxi** [comment]
but the entry point , that url has gone - at least that api/10 is no longer available an shows an 404 error. 

But I will give it a try in my sensors yaml file.

**Comment by typxxi** [comment]
und nun wieder zurück unter DE-LU

wieder das alte Bild der fehlenden Sensoren, so dass man nur sagen kann:

Die API scheint irgendwie irgendwas zu liefern für GER, was aber nicht passt zu meinem Standort und Tibber Preisen. 
Also nur ein Teilerfolg. 
Meine Nordpool Tibber Preise in HA hatten zuvor aber zu den Tibber App Preisen gepasst.

![image](https://github.com/user-attachments/assets/2ee139e4-3b5c-4a79-8a6a-602624148e1a)

**Comment by typxxi** [comment]
Is there an alternative source for tibber prices ?
I will write a complain to tibber that the tibber HA integration is no longer working which it was when I had signed the contract.

And I guess we all shoud do that to put pressure on tibber to deliver now and not some times in the unknown future.

**Comment by Brandyellow** [comment]
I updated the integration in HACS. After reloading it works perfectly.

**Comment by typxxi** [comment]
> I updated the integration in HACS. After reloading it works perfectly.

What do you mean with reloading ?
I have now installed 0.0.15

But I got an error during reboot in my notifications

2024-10-15 17:04:30.930 DEBUG (MainThread) [custom_components.nordpool.sensor] Dumping config mappingproxy({'region': 'DE-LU', 'currency': 'EUR', 'VAT': True, 'precision': 3, 'low_price_cutoff': 1.0, 'price_in_cents': True, 'price_type': 'kWh', 'additional_costs': '{{ (0.202 + (current_price * 0.19)) | float }}'})
2024-10-15 17:04:30.930 DEBUG (MainThread) [custom_components.nordpool.sensor] timezone set in ha 'Europe/Berlin'

**Comment by steinkjer73** [comment]
The region settings have been changed, I had to change my 3 sensors region settings in core.config.entries from Tr.Heim to NO3 in norway to get it working again. After restart 3 new sensors came up and online again. It also seems to be working if you delete old nordpool sensors and add new one.
![Capture](https://github.com/user-attachments/assets/83f9dacf-15ba-47e4-8e71-ceaf75a052f3)

**Comment by tmikoss** [comment]
Chiming in - had the same issue with 0.0.14, update to 0.0.15 has fixed it. Latvia region, did not have to update configuration.

**Comment by typxxi** [comment]
> Chiming in - had the same issue with 0.0.14, update to 0.0.15 has fixed it. Latvia region, did not have to update configuration.

I had updated too today but after 2 reboots nothing had changed, the sensor was still unavailable.

**Comment by michaelehlers** [comment]
@typxxi thanks for checking. I think it's two problems. The first being that obviously an update to newest version is necessary but also for some regions including germany there is some additional change. I am back home now and will play around with it to see if I get it working and valid prices.

**Comment by michaelehlers** [comment]
I now changed my config (in fact re-installed the integration and configured GER instead of DE-LU) and sesor same as for you @typxxi works n´again. I would assume that I was right with my guess that they changed the region 'code' for germany. I also compared my charts with the actual tibber prices and the graph pattern is 100% right for me (comparing to tibber, again). Only 'problem' that the prices do not match (as you said). I already had differences before, never got it to match 100% but now it seems that the difference between the nordpool prices and tibber is bigger, between 2,3 and 1,8 ct for tomorrow depending on the price being high or low (with same setting for 'additional cost). I will again play around a bit with additional cost and see if it still is applied (or if maybe there is a problem, because I lookedup DE-LU and that value is also in some js code). If I get the values to halfway match I am ok.

I think those code changes (and docs) will have to be implemented and updated  one day

**Comment by typxxi** [comment]
Meanwhile I reinstalled the tibber custom integration  and also copied the token again.

It works and the prices are spot on, but now I have to get those prices here into the chart again, which I had been using for quite a while and all are familiar too.

On the top of the screenshot in the middle you can see the current price of 27.08 cent price is the same in the tibber app for the third last hour of the day (makes it easier to find that in the long list of figures).

![image](https://github.com/user-attachments/assets/6184b801-ccce-4421-87eb-45fa14c51937)

Any ideas or suggestions to get that tibber sensor data to power the chart ?

**Comment by phsdv** [comment]
Norway also has issues
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/nordpool/sensor.py", line 129, in async_setup_entry
    _dry_setup(hass, config, async_add_devices)
  File "/config/custom_components/nordpool/sensor.py", line 104, in _dry_setup
    sensor = NordpoolSensor(
             ^^^^^^^^^^^^^^^
  File "/config/custom_components/nordpool/sensor.py", line 166, in __init__
    self._vat = _REGIONS[area][2]
                ~~~~~~~~^^^^^^
KeyError: 'Oslo'
```

**Comment by typxxi** [comment]
So I have moved back to the tibber implementation using [this integration](https://github.com/Danielhiversen/home_assistant_tibber_custom)


and then [this rest sensor and apex chart](https://community.simon42.com/t/tibber-in-dashboard-anzeigen/17816/6) and improved it a bit
![image](https://github.com/user-attachments/assets/e66336b9-93a7-4d2a-81f2-6ad49d951c5f)


**ATTENTION:** the following code has not been cleaned, therefore these explanations
 
It is designed to be used for the prices of tomorrow and the chart is hidden, if it is before 1 pm release time of the prices for tomorrow. The hiding is realised by an input helper.  An automation will set the input helper = 1 at 1 pm, at midnight another automation will reset it to 0 again.

If it is before 1 pm then there is a message to be patient till 1 pm till the new prices will be released.

Those protected spaces around "now" are used to make the marker bigger and more visible but DO NOT work for this code as that is for tomorrow only and NOW will never match with tomorrow, but I keep the code the same in both graphs. 

```
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: conditional
            conditions:
              - condition: numeric_state
                entity: input_number.tibber_morgige_preise_verfugbar
                below: 1
                above: -1
            card:
              type: horizontal-stack
              cards:
                - type: markdown
                  content: |-
                    {% set uhrzeit = now().strftime('%H:%M:%S') %}
                    # UM 13 UHR WERDEN
                    # DIE "1 TAG IM VORAUS"  
                    # BÖRSEN STROM PREISE 
                    # VERÖFFENTLICHT 
                    {{ "\n\n" }}
                    # Es ist jetzt {{ uhrzeit }}
                    # BITTE NOCH EIN WENIG GEDULD
          - type: conditional
            conditions:
              - condition: numeric_state
                entity: input_number.tibber_morgige_preise_verfugbar
                above: 0
                below: 2
            card:
              type: horizontal-stack
              cards:
                - type: custom:apexcharts-card
                  experimental:
                    color_threshold: true
                  all_series_config:
                    unit: "\_\_Cent / kWh"
                  apex_config:
                    grid:
                      show: true
                      borderColor: black
                    chart:
                      height: 250px
                    tooltip:
                      enabled: true
                      followCursor: false
                      x:
                        show: false
                      fixed:
                        enabled: true
                  graph_span: 24h
                  span:
                    start: day
                    offset: +1d
                  now:
                    show: true
                    label: "\_\_\_\_ J\_\_E\_\_T\_\_Z\_\_T \_\_\_\_"
                  header:
                    show: true
                    title: ""
                    show_states: true
                    colorize_states: true
                    standard_format: false
                  yaxis:
                    - min: 10
                      max: ~50
                      decimals: 0
                      apex_config:
                        tickAmount: 4
                  series:
                    - entity: sensor.tibber_prices
                      name: Preis
                      show:
                        in_header: before_now
                        name_in_header: false
                        extremas: true
                      color_threshold:
                        - value: 0
                          color: 4DD0E1
                        - value: 10
                          color: 26A69A
                        - value: 15
                          color: 4CAF50
                        - value: 20
                          color: 7CB342
                        - value: 25
                          color: FBC02D
                        - value: 30
                          color: EF6C00
                        - value: 40
                          color: B71C1C
                      type: line
                      curve: stepline
                      extend_to: false
                      stroke_width: 2
                      float_precision: 1
                      data_generator: >
                        const noon = new Date()

                        noon.setHours(0, 0, 0, 0)

                        const prices =
                        entity.attributes.today.concat(entity.attributes.tomorrow);

                        const data = [];

                        for(let i = 0; i < prices.length; i++) {
                          data.push([noon.getTime() + i * 1000 * 3600, prices[i].total * 100])
                        }

                        return data;
    title: "TIBBER: MORGIGE PREISE [C / kWh]"
```
