### ISSUE TITLE
Seems like only 23 "hours" gets collected

### ISSUE THREAD

**Issue by sknsean** [custom-components/nordpool#45]
Prices are correct but I'm missing price from 0:00 - 1:00 :(

```
{{ utcnow() }}
{{ now() }}
{{ utcnow().astimezone() }}
{{ now().astimezone() }}
{{ utcnow().tzinfo }}
{{ now().tzinfo }}
{{ now().astimezone().tzinfo }}
```
->
```
2020-11-24 12:49:00.000964+00:00
2020-11-24 13:49:00.001076+01:00
2020-11-24 13:49:00.001203+01:00
2020-11-24 13:49:00.001422+01:00
UTC
Europe/Copenhagen
CET
```
![Screenshot from 2020-11-24 13-43-07](https://user-images.githubusercontent.com/12713608/100095711-33bf2a80-2e5b-11eb-9b66-d78bfa6e1468.png)
![Screenshot from 2020-11-24 13-50-24](https://user-images.githubusercontent.com/12713608/100096301-1d659e80-2e5c-11eb-980d-d4f29bbf6b18.png)
![Screenshot from 2020-11-24 13-50-36](https://user-images.githubusercontent.com/12713608/100096312-1f2f6200-2e5c-11eb-84d2-2c74b44a8607.png)

Maybe it's related to https://github.com/custom-components/nordpool/issues/31

**Comment by Hellowlol** [comment]
Thanks! Can you post the raw today and raw tomorrow? Not as a image please :)

**Comment by sknsean** [comment]
```
current_price: 4.58
average: 3.739
off peak 1: 1.677
off peak 2: 3.815
peak: 5.273
min: 1.102
max: 11.76
unit: kWh
currency: DKK
country: Denmark
region: DK1
low price: false
tomorrow_valid: true
today:
  - 1.11
  - 1.102
  - 1.102
  - 1.11
  - 1.125
  - 1.259
  - 3.307
  - 3.299
  - 3.009
  - 5.459
  - 2.607
  - 2.636
  - 3.039
  - 4.58
  - 5.973
  - 6.129
  - 11.76
  - 5.973
  - 5.169
  - 4.804
  - 4.446
  - 3.716
  - 3.284
tomorrow:
  - 3.074
  - 3.022
  - 2.963
  - 3.022
  - 3.387
  - 3.945
  - 4.697
  - 4.794
  - 4.764
  - 4.451
  - 4.585
  - 4.414
  - 4.652
  - 7.451
  - 7.511
  - 11.084
  - 30.803
  - 42.877
  - 30.788
  - 30.751
  - 30.758
  - 11.404
  - 5.985
raw_today:
  - start: '2020-11-24T01:00:00+01:00'
    end: '2020-11-24T02:00:00+01:00'
    value: 1.11
  - start: '2020-11-24T02:00:00+01:00'
    end: '2020-11-24T03:00:00+01:00'
    value: 1.102
  - start: '2020-11-24T03:00:00+01:00'
    end: '2020-11-24T04:00:00+01:00'
    value: 1.102
  - start: '2020-11-24T04:00:00+01:00'
    end: '2020-11-24T05:00:00+01:00'
    value: 1.11
  - start: '2020-11-24T05:00:00+01:00'
    end: '2020-11-24T06:00:00+01:00'
    value: 1.125
  - start: '2020-11-24T06:00:00+01:00'
    end: '2020-11-24T07:00:00+01:00'
    value: 1.259
  - start: '2020-11-24T07:00:00+01:00'
    end: '2020-11-24T08:00:00+01:00'
    value: 3.307
  - start: '2020-11-24T08:00:00+01:00'
    end: '2020-11-24T09:00:00+01:00'
    value: 3.299
  - start: '2020-11-24T09:00:00+01:00'
    end: '2020-11-24T10:00:00+01:00'
    value: 3.009
  - start: '2020-11-24T10:00:00+01:00'
    end: '2020-11-24T11:00:00+01:00'
    value: 5.459
  - start: '2020-11-24T11:00:00+01:00'
    end: '2020-11-24T12:00:00+01:00'
    value: 2.607
  - start: '2020-11-24T12:00:00+01:00'
    end: '2020-11-24T13:00:00+01:00'
    value: 2.636
  - start: '2020-11-24T13:00:00+01:00'
    end: '2020-11-24T14:00:00+01:00'
    value: 3.039
  - start: '2020-11-24T14:00:00+01:00'
    end: '2020-11-24T15:00:00+01:00'
    value: 4.58
  - start: '2020-11-24T15:00:00+01:00'
    end: '2020-11-24T16:00:00+01:00'
    value: 5.973
  - start: '2020-11-24T16:00:00+01:00'
    end: '2020-11-24T17:00:00+01:00'
    value: 6.129
  - start: '2020-11-24T17:00:00+01:00'
    end: '2020-11-24T18:00:00+01:00'
    value: 11.76
  - start: '2020-11-24T18:00:00+01:00'
    end: '2020-11-24T19:00:00+01:00'
    value: 5.973
  - start: '2020-11-24T19:00:00+01:00'
    end: '2020-11-24T20:00:00+01:00'
    value: 5.169
  - start: '2020-11-24T20:00:00+01:00'
    end: '2020-11-24T21:00:00+01:00'
    value: 4.804
  - start: '2020-11-24T21:00:00+01:00'
    end: '2020-11-24T22:00:00+01:00'
    value: 4.446
  - start: '2020-11-24T22:00:00+01:00'
    end: '2020-11-24T23:00:00+01:00'
    value: 3.716
  - start: '2020-11-24T23:00:00+01:00'
    end: '2020-11-25T00:00:00+01:00'
    value: 3.284
raw_tomorrow:
  - start: '2020-11-25T01:00:00+01:00'
    end: '2020-11-25T02:00:00+01:00'
    value: 3.074
  - start: '2020-11-25T02:00:00+01:00'
    end: '2020-11-25T03:00:00+01:00'
    value: 3.022
  - start: '2020-11-25T03:00:00+01:00'
    end: '2020-11-25T04:00:00+01:00'
    value: 2.963
  - start: '2020-11-25T04:00:00+01:00'
    end: '2020-11-25T05:00:00+01:00'
    value: 3.022
  - start: '2020-11-25T05:00:00+01:00'
    end: '2020-11-25T06:00:00+01:00'
    value: 3.387
  - start: '2020-11-25T06:00:00+01:00'
    end: '2020-11-25T07:00:00+01:00'
    value: 3.945
  - start: '2020-11-25T07:00:00+01:00'
    end: '2020-11-25T08:00:00+01:00'
    value: 4.697
  - start: '2020-11-25T08:00:00+01:00'
    end: '2020-11-25T09:00:00+01:00'
    value: 4.794
  - start: '2020-11-25T09:00:00+01:00'
    end: '2020-11-25T10:00:00+01:00'
    value: 4.764
  - start: '2020-11-25T10:00:00+01:00'
    end: '2020-11-25T11:00:00+01:00'
    value: 4.451
  - start: '2020-11-25T11:00:00+01:00'
    end: '2020-11-25T12:00:00+01:00'
    value: 4.585
  - start: '2020-11-25T12:00:00+01:00'
    end: '2020-11-25T13:00:00+01:00'
    value: 4.414
  - start: '2020-11-25T13:00:00+01:00'
    end: '2020-11-25T14:00:00+01:00'
    value: 4.652
  - start: '2020-11-25T14:00:00+01:00'
    end: '2020-11-25T15:00:00+01:00'
    value: 7.451
  - start: '2020-11-25T15:00:00+01:00'
    end: '2020-11-25T16:00:00+01:00'
    value: 7.511
  - start: '2020-11-25T16:00:00+01:00'
    end: '2020-11-25T17:00:00+01:00'
    value: 11.084
  - start: '2020-11-25T17:00:00+01:00'
    end: '2020-11-25T18:00:00+01:00'
    value: 30.803
  - start: '2020-11-25T18:00:00+01:00'
    end: '2020-11-25T19:00:00+01:00'
    value: 42.877
  - start: '2020-11-25T19:00:00+01:00'
    end: '2020-11-25T20:00:00+01:00'
    value: 30.788
  - start: '2020-11-25T20:00:00+01:00'
    end: '2020-11-25T21:00:00+01:00'
    value: 30.751
  - start: '2020-11-25T21:00:00+01:00'
    end: '2020-11-25T22:00:00+01:00'
    value: 30.758
  - start: '2020-11-25T22:00:00+01:00'
    end: '2020-11-25T23:00:00+01:00'
    value: 11.404
  - start: '2020-11-25T23:00:00+01:00'
    end: '2020-11-26T00:00:00+01:00'
    value: 5.985
unit_of_measurement: Øre/kWh
friendly_name: nordpool_kwh_dk1_dkk_3_095_0
icon: 'mdi:flash'
```

**Comment by Hellowlol** [comment]
Can you take a picture of off your config and try reboot hass?

**Comment by sknsean** [comment]
Home-Assistant version: 0.118.2
This component version: fe202bf4472ff2061cc3c3f0b9ee3765272cf7cc
Home-Assistant sensor config:
```
  - platform: nordpool
    VAT: False
    currency: "DKK"
    low_price_cutoff: 0.95
    region: "DK1"
    precision: 3
    price_type: kWh
    price_in_cents: True
    friendly_name: "Power price"
```
I'm using the home-assistant docker image `homeassistant/home-assistant:stable`

**Comment by sknsean** [comment]
After restart the docker container:
```
current_price: 4.697
average: null
off peak 1: 3.613
off peak 2: null
peak: 9.369
min: 2.963
max: null
unit: kWh
currency: DKK
country: Denmark
region: DK1
low price: null
tomorrow_valid: true
today:
  - 3.074
  - 3.022
  - 2.963
  - 3.022
  - 3.387
  - 3.945
  - 4.697
  - 4.794
  - 4.764
  - 4.451
  - 4.585
  - 4.414
  - 4.652
  - 7.451
  - 7.511
  - 11.084
  - 30.803
  - 42.877
  - 30.788
  - 30.751
  - 30.758
  - 11.404
  - 5.985
  - null
tomorrow:
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
  - null
raw_today:
  - start: '2020-11-25T01:00:00+01:00'
    end: '2020-11-25T02:00:00+01:00'
    value: 3.074
  - start: '2020-11-25T02:00:00+01:00'
    end: '2020-11-25T03:00:00+01:00'
    value: 3.022
  - start: '2020-11-25T03:00:00+01:00'
    end: '2020-11-25T04:00:00+01:00'
    value: 2.963
  - start: '2020-11-25T04:00:00+01:00'
    end: '2020-11-25T05:00:00+01:00'
    value: 3.022
  - start: '2020-11-25T05:00:00+01:00'
    end: '2020-11-25T06:00:00+01:00'
    value: 3.387
  - start: '2020-11-25T06:00:00+01:00'
    end: '2020-11-25T07:00:00+01:00'
    value: 3.945
  - start: '2020-11-25T07:00:00+01:00'
    end: '2020-11-25T08:00:00+01:00'
    value: 4.697
  - start: '2020-11-25T08:00:00+01:00'
    end: '2020-11-25T09:00:00+01:00'
    value: 4.794
  - start: '2020-11-25T09:00:00+01:00'
    end: '2020-11-25T10:00:00+01:00'
    value: 4.764
  - start: '2020-11-25T10:00:00+01:00'
    end: '2020-11-25T11:00:00+01:00'
    value: 4.451
  - start: '2020-11-25T11:00:00+01:00'
    end: '2020-11-25T12:00:00+01:00'
    value: 4.585
  - start: '2020-11-25T12:00:00+01:00'
    end: '2020-11-25T13:00:00+01:00'
    value: 4.414
  - start: '2020-11-25T13:00:00+01:00'
    end: '2020-11-25T14:00:00+01:00'
    value: 4.652
  - start: '2020-11-25T14:00:00+01:00'
    end: '2020-11-25T15:00:00+01:00'
    value: 7.451
  - start: '2020-11-25T15:00:00+01:00'
    end: '2020-11-25T16:00:00+01:00'
    value: 7.511
  - start: '2020-11-25T16:00:00+01:00'
    end: '2020-11-25T17:00:00+01:00'
    value: 11.084
  - start: '2020-11-25T17:00:00+01:00'
    end: '2020-11-25T18:00:00+01:00'
    value: 30.803
  - start: '2020-11-25T18:00:00+01:00'
    end: '2020-11-25T19:00:00+01:00'
    value: 42.877
  - start: '2020-11-25T19:00:00+01:00'
    end: '2020-11-25T20:00:00+01:00'
    value: 30.788
  - start: '2020-11-25T20:00:00+01:00'
    end: '2020-11-25T21:00:00+01:00'
    value: 30.751
  - start: '2020-11-25T21:00:00+01:00'
    end: '2020-11-25T22:00:00+01:00'
    value: 30.758
  - start: '2020-11-25T22:00:00+01:00'
    end: '2020-11-25T23:00:00+01:00'
    value: 11.404
  - start: '2020-11-25T23:00:00+01:00'
    end: '2020-11-26T00:00:00+01:00'
    value: 5.985
  - start: '2020-11-26T00:00:00+01:00'
    end: '2020-11-26T01:00:00+01:00'
    value: null
raw_tomorrow:
  - start: '2020-11-26T01:00:00+01:00'
    end: '2020-11-26T02:00:00+01:00'
    value: null
  - start: '2020-11-26T02:00:00+01:00'
    end: '2020-11-26T03:00:00+01:00'
    value: null
  - start: '2020-11-26T03:00:00+01:00'
    end: '2020-11-26T04:00:00+01:00'
    value: null
  - start: '2020-11-26T04:00:00+01:00'
    end: '2020-11-26T05:00:00+01:00'
    value: null
  - start: '2020-11-26T05:00:00+01:00'
    end: '2020-11-26T06:00:00+01:00'
    value: null
  - start: '2020-11-26T06:00:00+01:00'
    end: '2020-11-26T07:00:00+01:00'
    value: null
  - start: '2020-11-26T07:00:00+01:00'
    end: '2020-11-26T08:00:00+01:00'
    value: null
  - start: '2020-11-26T08:00:00+01:00'
    end: '2020-11-26T09:00:00+01:00'
    value: null
  - start: '2020-11-26T09:00:00+01:00'
    end: '2020-11-26T10:00:00+01:00'
    value: null
  - start: '2020-11-26T10:00:00+01:00'
    end: '2020-11-26T11:00:00+01:00'
    value: null
  - start: '2020-11-26T11:00:00+01:00'
    end: '2020-11-26T12:00:00+01:00'
    value: null
  - start: '2020-11-26T12:00:00+01:00'
    end: '2020-11-26T13:00:00+01:00'
    value: null
  - start: '2020-11-26T13:00:00+01:00'
    end: '2020-11-26T14:00:00+01:00'
    value: null
  - start: '2020-11-26T14:00:00+01:00'
    end: '2020-11-26T15:00:00+01:00'
    value: null
  - start: '2020-11-26T15:00:00+01:00'
    end: '2020-11-26T16:00:00+01:00'
    value: null
  - start: '2020-11-26T16:00:00+01:00'
    end: '2020-11-26T17:00:00+01:00'
    value: null
  - start: '2020-11-26T17:00:00+01:00'
    end: '2020-11-26T18:00:00+01:00'
    value: null
  - start: '2020-11-26T18:00:00+01:00'
    end: '2020-11-26T19:00:00+01:00'
    value: null
  - start: '2020-11-26T19:00:00+01:00'
    end: '2020-11-26T20:00:00+01:00'
    value: null
  - start: '2020-11-26T20:00:00+01:00'
    end: '2020-11-26T21:00:00+01:00'
    value: null
  - start: '2020-11-26T21:00:00+01:00'
    end: '2020-11-26T22:00:00+01:00'
    value: null
  - start: '2020-11-26T22:00:00+01:00'
    end: '2020-11-26T23:00:00+01:00'
    value: null
  - start: '2020-11-26T23:00:00+01:00'
    end: '2020-11-27T00:00:00+01:00'
    value: null
unit_of_measurement: Øre/kWh
friendly_name: nordpool_kwh_dk1_dkk_3_095_0
icon: 'mdi:flash'
```
I usually restart hass from the configuration menu
