### ISSUE TITLE
Check return currency before accepting data

### ISSUE THREAD

**Issue by jschlyter** [custom-components/nordpool#52]
## Version of the custom_component

- https://github.com/custom-components/nordpool/commit/f7bd8c1

## Configuration

```yaml
sensor:

  - platform: nordpool
    VAT: true
    currency: SEK
    low_price_cutoff: 0.95
    region: SE3
    precision: 3
    price_type: kWh
```

## Describe the bug

The component currently assumes that if you query for currency X, the result will contain prices in currency X. For several reasons, including https://github.com/kipe/nordpool/issues/17, this may not be true and it would be most useful if the component could reject data in the wrong currency. No further information should be required.

Fixing this would not have prevented, but would have mitigated, #51
