### ISSUE TITLE
Friendly name not used when configured using config_flow

### ISSUE THREAD

**Issue by fredrikbaberg** [custom-components/nordpool#66]
## Version of the custom_component

Version 0.0.3

## Configuration

```yaml

Installed from HACS, using configuration flow, so no YAML to copy.

Region: SE3
Currency: SEK
Friendly name: Elpris

Other values are left at default.

```

## Describe the bug

Setting `friendly name` during configuration flow (adding through Integrations) does not apply to sensor.
I have not tried if it works with yaml.

## Debug log

```text

No relevant log. Last lines of sensor:

unit_of_measurement: SEK/kWh
friendly_name: nordpool_kwh_se3_sek_3_10_025
icon: mdi:flash

```
