### ISSUE TITLE
Exception in check_stuff when dispatching 'nordpool_update

### ISSUE THREAD

**Issue by olealm** [custom-components/nordpool#68]
## Version of the custom_component

0.0.3

## Configuration

```  
sensor:
- platform: nordpool
    VAT: true
    currency: "NOK"
    low_price_cutoff: 0.90
    region: "Bergen"
    precision: 2
    friendly_name: "Nordpool"


```
`Exception in check_stuff when dispatching 'nordpool_update': () Traceback (most recent call last): File "/config/custom_components/nordpool/sensor.py", line 477, in check_stuff self.async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state self._async_write_ha_state() File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state sstate = self.state File "/config/custom_components/nordpool/sensor.py", line 239, in state return self.current_price File "/config/custom_components/nordpool/sensor.py", line 324, in current_price res = self._calc_price() File "/config/custom_components/nordpool/sensor.py", line 277, in _calc_price price = template_value + value / _PRICE_IN[self._price_type] * ( TypeError: can only concatenate str (not "float") to str
`
## Describe the bug
Sensor 'Unavailable'

## Debug log

```text

```
