### ISSUE TITLE
Friendly name attribute doesn't work.

### ISSUE THREAD

**Issue by kaar372** [custom-components/nordpool#74]
## Version of the custom_component

0.0.3

## Configuration

```yaml

nordpool:

sensor:
  - platform: nordpool
    friendly_name: "Elektri hind"

    # Should the prices include vat? Default True
    VAT: false

    # What currency the api fetches the prices in
    # this is only need if you want a sensor in a non local currecy
    currency: "EUR"

    # Helper so you can set your "low" price
    # low_price = hour_price < average * low_price_cutoff
    # low_price_cutoff: 0.95

    # What power regions your are interested in.
    # Possible values: "DK1", "DK2", "FI", "LT", "LV", "Oslo", "Kr.sand", "Bergen", "Molde", "Tr.heim", "Tromsø", "SE1", "SE2", "SE3","SE4", "SYS", "EE"
    region: "EE"

    # How many decimals to use in the display of the price
    precision: 5

    # What the price should be displayed in default
    # Possible values: MWh, kWh and Wh
    # default: kWh
    price_type: kWh

```

## Describe the bug
Friendly name attribute doesn't work.

State: value and attributes:
<html>
<body>

sensor.nordpool_kwh_ee_eur_5_10_0nordpool_kwh_ee_eur_5_10_0 | 0.10876 | current_price: 0.10876 average: 0.10255 off peak 1: 0.08309 off peak 2: 0.09772 peak: 0.12122 min: 0.07572 max: 0.13008 unit: kWh currency: EUR country: Estonia region: EE low price: false tomorrow_valid: true today: 0.0796, 0.08051, 0.07683, 0.07581, 0.07572, 0.078, 0.09537, 0.10284, 0.10512, 0.10944, 0.12884, 0.12884, 0.1289, 0.13008, 0.12882, 0.10876, 0.10607, 0.10964, 0.10897, 0.11217, 0.10323, 0.0963, 0.09825, 0.09308 tomorrow: 0.08517, 0.07914, 0.05395, 0.07313, 0.05308, 0.05312, 0.07673, 0.09388, 0.10187, 0.10159, 0.10704, 0.10512, 0.10464, 0.10376, 0.10224, 0.10195, 0.10264, 0.10346, 0.10215, 0.10461, 0.10254, 0.09693, 0.0961, 0.09117 raw_today:  - start: '2021-07-15T00:00:00+03:00'   end: '2021-07-15T01:00:00+03:00'   value: 0.0796 - start: '2021-07-15T01:00:00+03:00'   end: '2021-07-15T02:00:00+03:00'   value: 0.08051 - start: '2021-07-15T02:00:00+03:00'   end: '2021-07-15T03:00:00+03:00'   value: 0.07683 - start: '2021-07-15T03:00:00+03:00'   end: '2021-07-15T04:00:00+03:00'   value: 0.07581 - start: '2021-07-15T04:00:00+03:00'   end: '2021-07-15T05:00:00+03:00'   value: 0.07572 - start: '2021-07-15T05:00:00+03:00'   end: '2021-07-15T06:00:00+03:00'   value: 0.078 - start: '2021-07-15T06:00:00+03:00'   end: '2021-07-15T07:00:00+03:00'   value: 0.09537 - start: '2021-07-15T07:00:00+03:00'   end: '2021-07-15T08:00:00+03:00'   value: 0.10284 - start: '2021-07-15T08:00:00+03:00'   end: '2021-07-15T09:00:00+03:00'   value: 0.10512 - start: '2021-07-15T09:00:00+03:00'   end: '2021-07-15T10:00:00+03:00'   value: 0.10944 - start: '2021-07-15T10:00:00+03:00'   end: '2021-07-15T11:00:00+03:00'   value: 0.12884 - start: '2021-07-15T11:00:00+03:00'   end: '2021-07-15T12:00:00+03:00'   value: 0.12884 - start: '2021-07-15T12:00:00+03:00'   end: '2021-07-15T13:00:00+03:00'   value: 0.1289 - start: '2021-07-15T13:00:00+03:00'   end: '2021-07-15T14:00:00+03:00'   value: 0.13008 - start: '2021-07-15T14:00:00+03:00'   end: '2021-07-15T15:00:00+03:00'   value: 0.12882 - start: '2021-07-15T15:00:00+03:00'   end: '2021-07-15T16:00:00+03:00'   value: 0.10876 - start: '2021-07-15T16:00:00+03:00'   end: '2021-07-15T17:00:00+03:00'   value: 0.10607 - start: '2021-07-15T17:00:00+03:00'   end: '2021-07-15T18:00:00+03:00'   value: 0.10964 - start: '2021-07-15T18:00:00+03:00'   end: '2021-07-15T19:00:00+03:00'   value: 0.10897 - start: '2021-07-15T19:00:00+03:00'   end: '2021-07-15T20:00:00+03:00'   value: 0.11217 - start: '2021-07-15T20:00:00+03:00'   end: '2021-07-15T21:00:00+03:00'   value: 0.10323 - start: '2021-07-15T21:00:00+03:00'   end: '2021-07-15T22:00:00+03:00'   value: 0.0963 - start: '2021-07-15T22:00:00+03:00'   end: '2021-07-15T23:00:00+03:00'   value: 0.09825 - start: '2021-07-15T23:00:00+03:00'   end: '2021-07-16T00:00:00+03:00'   value: 0.09308  raw_tomorrow:  - start: '2021-07-16T00:00:00+03:00'   end: '2021-07-16T01:00:00+03:00'   value: 0.08517 - start: '2021-07-16T01:00:00+03:00'   end: '2021-07-16T02:00:00+03:00'   value: 0.07914 - start: '2021-07-16T02:00:00+03:00'   end: '2021-07-16T03:00:00+03:00'   value: 0.05395 - start: '2021-07-16T03:00:00+03:00'   end: '2021-07-16T04:00:00+03:00'   value: 0.07313 - start: '2021-07-16T04:00:00+03:00'   end: '2021-07-16T05:00:00+03:00'   value: 0.05308 - start: '2021-07-16T05:00:00+03:00'   end: '2021-07-16T06:00:00+03:00'   value: 0.05312 - start: '2021-07-16T06:00:00+03:00'   end: '2021-07-16T07:00:00+03:00'   value: 0.07673 - start: '2021-07-16T07:00:00+03:00'   end: '2021-07-16T08:00:00+03:00'   value: 0.09388 - start: '2021-07-16T08:00:00+03:00'   end: '2021-07-16T09:00:00+03:00'   value: 0.10187 - start: '2021-07-16T09:00:00+03:00'   end: '2021-07-16T10:00:00+03:00'   value: 0.10159 - start: '2021-07-16T10:00:00+03:00'   end: '2021-07-16T11:00:00+03:00'   value: 0.10704 - start: '2021-07-16T11:00:00+03:00'   end: '2021-07-16T12:00:00+03:00'   value: 0.10512 - start: '2021-07-16T12:00:00+03:00'   end: '2021-07-16T13:00:00+03:00'   value: 0.10464 - start: '2021-07-16T13:00:00+03:00'   end: '2021-07-16T14:00:00+03:00'   value: 0.10376 - start: '2021-07-16T14:00:00+03:00'   end: '2021-07-16T15:00:00+03:00'   value: 0.10224 - start: '2021-07-16T15:00:00+03:00'   end: '2021-07-16T16:00:00+03:00'   value: 0.10195 - start: '2021-07-16T16:00:00+03:00'   end: '2021-07-16T17:00:00+03:00'   value: 0.10264 - start: '2021-07-16T17:00:00+03:00'   end: '2021-07-16T18:00:00+03:00'   value: 0.10346 - start: '2021-07-16T18:00:00+03:00'   end: '2021-07-16T19:00:00+03:00'   value: 0.10215 - start: '2021-07-16T19:00:00+03:00'   end: '2021-07-16T20:00:00+03:00'   value: 0.10461 - start: '2021-07-16T20:00:00+03:00'   end: '2021-07-16T21:00:00+03:00'   value: 0.10254 - start: '2021-07-16T21:00:00+03:00'   end: '2021-07-16T22:00:00+03:00'   value: 0.09693 - start: '2021-07-16T22:00:00+03:00'   end: '2021-07-16T23:00:00+03:00'   value: 0.0961 - start: '2021-07-16T23:00:00+03:00'   end: '2021-07-17T00:00:00+03:00'   value: 0.09117  unit_of_measurement: EUR/kWh friendly_name: nordpool_kwh_ee_eur_5_10_0 icon: mdi:flash
-- | -- | --

</body>
</html>
