### ISSUE TITLE
Tomorrow valid flag

### ISSUE THREAD

**Issue by ollan** [custom-components/nordpool#82]
It seems that the "Tomorrow valid" flag does not work properly. I use SE3 region and also this morning the flag showed "true" value.
One proposal would be to look through all values in tomorrow array. If all 24 values are filled than set "tomorrow valid" to "true".

**Comment by Hellowlol** [comment]
I have never seen this before. Usually things will blow up and create a exception. Disk you see anything in the log?

**Comment by ollan** [comment]
No log occured.
I will try to get some data tomorrow morning when "tomorrow_valid" should not be "true".

**Comment by Repsionu** [comment]
I can confirm erratic behavior of "tomorrow_valid" after DST change :-(
After midnight it changes to "True" as data here (Estonia) has data for 1.00 hour...
Setting it manually to "False" hides my conditional card but after todays update (ca. 14.00) it is not changed.
Best, JR

**Comment by ThoStaKa** [comment]
Same issue to me as well with latest version (0.0.4). 
Flag is set to true without data for tomorrow (time is 08:50)
No errors in log, tried reloading the integration and several reboots

**Comment by nord-** [comment]
When values for tomorrow all contains null, the `tomorrow_valid`-flag should be `false`.

Example of current behaviour:
```
tomorrow_valid: true
tomorrow:
  - null
raw_tomorrow:
  - start: '2022-01-28T00:00:00+01:00'
    end: '2022-01-28T01:00:00+01:00'
    value: null
```
