### ISSUE TITLE
Tomorrow data is same as today data

### ISSUE THREAD

**Issue by sim642** [custom-components/nordpool#84]
## Version of the custom_component

0.0.3

## Configuration

Configured via UI.

## Describe the bug
Today's data is duplicated under tomorrow's data, using today's times.
This is before tomorrow's Nordpool prices have been published. Usually `raw_tomorrow` is then empty, but somehow it may also copy `raw_today`.

```
current_price: 0.097
average: 0.107
off peak 1: 0.084
off peak 2: 0.139
peak: 0.101
min: 0.023
max: 0.214
unit: kWh
currency: EUR
country: Estonia
region: EE
low price: true
tomorrow_valid: false
today:
  - 0.106
  - 0.1
  - 0.023
  - 0.084
  - 0.088
  - 0.089
  - 0.096
  - 0.085
  - 0.091
  - 0.101
  - 0.108
  - 0.109
  - 0.097
  - 0.095
  - 0.104
  - 0.083
  - 0.108
  - 0.111
  - 0.134
  - 0.201
  - 0.214
  - 0.177
  - 0.13
  - 0.035
tomorrow:
  - 0.106
  - 0.1
  - 0.023
  - 0.084
  - 0.088
  - 0.089
  - 0.096
  - 0.085
  - 0.091
  - 0.101
  - 0.108
  - 0.109
  - 0.097
  - 0.095
  - 0.104
  - 0.083
  - 0.108
  - 0.111
  - 0.134
  - 0.201
  - 0.214
  - 0.177
  - 0.13
  - 0.035
raw_today:
  - start: '2021-10-10T00:00:00+03:00'
    end: '2021-10-10T01:00:00+03:00'
    value: 0.106
  - start: '2021-10-10T01:00:00+03:00'
    end: '2021-10-10T02:00:00+03:00'
    value: 0.1
  - start: '2021-10-10T02:00:00+03:00'
    end: '2021-10-10T03:00:00+03:00'
    value: 0.023
  - start: '2021-10-10T03:00:00+03:00'
    end: '2021-10-10T04:00:00+03:00'
    value: 0.084
  - start: '2021-10-10T04:00:00+03:00'
    end: '2021-10-10T05:00:00+03:00'
    value: 0.088
  - start: '2021-10-10T05:00:00+03:00'
    end: '2021-10-10T06:00:00+03:00'
    value: 0.089
  - start: '2021-10-10T06:00:00+03:00'
    end: '2021-10-10T07:00:00+03:00'
    value: 0.096
  - start: '2021-10-10T07:00:00+03:00'
    end: '2021-10-10T08:00:00+03:00'
    value: 0.085
  - start: '2021-10-10T08:00:00+03:00'
    end: '2021-10-10T09:00:00+03:00'
    value: 0.091
  - start: '2021-10-10T09:00:00+03:00'
    end: '2021-10-10T10:00:00+03:00'
    value: 0.101
  - start: '2021-10-10T10:00:00+03:00'
    end: '2021-10-10T11:00:00+03:00'
    value: 0.108
  - start: '2021-10-10T11:00:00+03:00'
    end: '2021-10-10T12:00:00+03:00'
    value: 0.109
  - start: '2021-10-10T12:00:00+03:00'
    end: '2021-10-10T13:00:00+03:00'
    value: 0.097
  - start: '2021-10-10T13:00:00+03:00'
    end: '2021-10-10T14:00:00+03:00'
    value: 0.095
  - start: '2021-10-10T14:00:00+03:00'
    end: '2021-10-10T15:00:00+03:00'
    value: 0.104
  - start: '2021-10-10T15:00:00+03:00'
    end: '2021-10-10T16:00:00+03:00'
    value: 0.083
  - start: '2021-10-10T16:00:00+03:00'
    end: '2021-10-10T17:00:00+03:00'
    value: 0.108
  - start: '2021-10-10T17:00:00+03:00'
    end: '2021-10-10T18:00:00+03:00'
    value: 0.111
  - start: '2021-10-10T18:00:00+03:00'
    end: '2021-10-10T19:00:00+03:00'
    value: 0.134
  - start: '2021-10-10T19:00:00+03:00'
    end: '2021-10-10T20:00:00+03:00'
    value: 0.201
  - start: '2021-10-10T20:00:00+03:00'
    end: '2021-10-10T21:00:00+03:00'
    value: 0.214
  - start: '2021-10-10T21:00:00+03:00'
    end: '2021-10-10T22:00:00+03:00'
    value: 0.177
  - start: '2021-10-10T22:00:00+03:00'
    end: '2021-10-10T23:00:00+03:00'
    value: 0.13
  - start: '2021-10-10T23:00:00+03:00'
    end: '2021-10-11T00:00:00+03:00'
    value: 0.035
raw_tomorrow:
  - start: '2021-10-10T00:00:00+03:00'
    end: '2021-10-10T01:00:00+03:00'
    value: 0.106
  - start: '2021-10-10T01:00:00+03:00'
    end: '2021-10-10T02:00:00+03:00'
    value: 0.1
  - start: '2021-10-10T02:00:00+03:00'
    end: '2021-10-10T03:00:00+03:00'
    value: 0.023
  - start: '2021-10-10T03:00:00+03:00'
    end: '2021-10-10T04:00:00+03:00'
    value: 0.084
  - start: '2021-10-10T04:00:00+03:00'
    end: '2021-10-10T05:00:00+03:00'
    value: 0.088
  - start: '2021-10-10T05:00:00+03:00'
    end: '2021-10-10T06:00:00+03:00'
    value: 0.089
  - start: '2021-10-10T06:00:00+03:00'
    end: '2021-10-10T07:00:00+03:00'
    value: 0.096
  - start: '2021-10-10T07:00:00+03:00'
    end: '2021-10-10T08:00:00+03:00'
    value: 0.085
  - start: '2021-10-10T08:00:00+03:00'
    end: '2021-10-10T09:00:00+03:00'
    value: 0.091
  - start: '2021-10-10T09:00:00+03:00'
    end: '2021-10-10T10:00:00+03:00'
    value: 0.101
  - start: '2021-10-10T10:00:00+03:00'
    end: '2021-10-10T11:00:00+03:00'
    value: 0.108
  - start: '2021-10-10T11:00:00+03:00'
    end: '2021-10-10T12:00:00+03:00'
    value: 0.109
  - start: '2021-10-10T12:00:00+03:00'
    end: '2021-10-10T13:00:00+03:00'
    value: 0.097
  - start: '2021-10-10T13:00:00+03:00'
    end: '2021-10-10T14:00:00+03:00'
    value: 0.095
  - start: '2021-10-10T14:00:00+03:00'
    end: '2021-10-10T15:00:00+03:00'
    value: 0.104
  - start: '2021-10-10T15:00:00+03:00'
    end: '2021-10-10T16:00:00+03:00'
    value: 0.083
  - start: '2021-10-10T16:00:00+03:00'
    end: '2021-10-10T17:00:00+03:00'
    value: 0.108
  - start: '2021-10-10T17:00:00+03:00'
    end: '2021-10-10T18:00:00+03:00'
    value: 0.111
  - start: '2021-10-10T18:00:00+03:00'
    end: '2021-10-10T19:00:00+03:00'
    value: 0.134
  - start: '2021-10-10T19:00:00+03:00'
    end: '2021-10-10T20:00:00+03:00'
    value: 0.201
  - start: '2021-10-10T20:00:00+03:00'
    end: '2021-10-10T21:00:00+03:00'
    value: 0.214
  - start: '2021-10-10T21:00:00+03:00'
    end: '2021-10-10T22:00:00+03:00'
    value: 0.177
  - start: '2021-10-10T22:00:00+03:00'
    end: '2021-10-10T23:00:00+03:00'
    value: 0.13
  - start: '2021-10-10T23:00:00+03:00'
    end: '2021-10-11T00:00:00+03:00'
    value: 0.035
unit_of_measurement: EUR/kWh
friendly_name: nordpool_kwh_ee_eur_3_10_02
icon: 'mdi:flash'

```
